### ISSUE TITLE
Crash while trying to add controls tiles.

### ISSUE THREAD

**Issue by EnderDragonEP** [KieronQuinn/ClassicPowerMenu#120]
Every time I'm trying to add a control tile to the power menu it'll instantly crash. No matter how many times I reinstall Google Home app or this app I just can't fix this issue.
I recently received a system update. I suspect the issue was caused by the update. I'm using OmniROM on Zenfone 6 android 13.

Here is the crash log:
```
FATAL EXCEPTION: main
Process: com.kieronquinn.app.classicpowermenu, PID: 27171
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kieronquinn.app.classicpowermenu/com.android.systemui.controls.management.ControlsFavoritingActivity}: android.view.InflateException: Binary XML file line #51 in com.kieronquinn.app.classicpowermenu:layout/controls_onboarding: Binary XML file line #51 in com.kieronquinn.app.classicpowermenu:layout/controls_onboarding: Error inflating class <unknown>
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3644)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.view.InflateException: Binary XML file line #51 in com.kieronquinn.app.classicpowermenu:layout/controls_onboarding: Binary XML file line #51 in com.kieronquinn.app.classicpowermenu:layout/controls_onboarding: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #51 in com.kieronquinn.app.classicpowermenu:layout/controls_onboarding: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createView(LayoutInflater.java:780)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at com.android.systemui.controls.TooltipManager.<init>(TooltipManager.kt:63)
	at com.android.systemui.controls.TooltipManager.<init>(TooltipManager.kt:47)
	at com.android.systemui.controls.management.ControlsFavoritingActivity.bindViews(ControlsFavoritingActivity.kt:257)
	at com.android.systemui.controls.management.ControlsFavoritingActivity.onCreate(ControlsFavoritingActivity.kt:137)
	at android.app.Activity.performCreate(Activity.java:8342)
	at android.app.Activity.performCreate(Activity.java:8321)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f04054a a=-1}, theme={InheritanceMap=[id=0x7f160262com.kieronquinn.app.classicpowermenu:style/Theme.ControlsManagement, id=0x1030129android:style/Theme.DeviceDefault.NoActionBar, id=0x103022eandroid:style/Theme.Material.NoActionBar, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[com.kieronquinn.app.classicpowermenu:style/Theme.ControlsManagement, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:600)
	at android.widget.TextView.readTextAppearance(TextView.java:4123)
	at android.widget.TextView.<init>(TextView.java:1165)
	at android.widget.TextView.<init>(TextView.java:1066)
	at android.widget.TextView.<init>(TextView.java:1062)
	... 36 more
```

**Comment by KieronQuinn** [comment]
#107
