### ISSUE TITLE
Crash while adding controls

### ISSUE THREAD

**Issue by EnderDragonEP** [KieronQuinn/ClassicPowerMenu#128]
After I added some controls and I went back to try adding some more, the interface will stuck on loading like the screenshot blow then crash afterward.

![Screenshot_20231028-065826](https://github.com/KieronQuinn/ClassicPowerMenu/assets/30905525/050aeeb3-1b8b-47c2-bd26-82eb98b554b3)

Crash log:
```
FATAL EXCEPTION: main
Process: com.kieronquinn.app.classicpowermenu, PID: 1208
java.lang.IllegalArgumentException: com.kieronquinn.app.classicpowermenu: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
	at android.app.PendingIntent.getActivity(PendingIntent.java:470)
	at android.app.PendingIntent.getActivity(PendingIntent.java:434)
	at com.android.systemui.controls.controller.ControlsControllerImpl.createRemovedStatus(ControlsControllerImpl.kt:471)
	at com.android.systemui.controls.controller.ControlsControllerImpl.access$createRemovedStatus(ControlsControllerImpl.kt:54)
	at com.android.systemui.controls.controller.ControlsControllerImpl$loadForComponent$2.error$lambda$8(ControlsControllerImpl.kt:346)
	at com.android.systemui.controls.controller.ControlsControllerImpl$loadForComponent$2.$r8$lambda$MKmKp5lW5HXenWfihOJPT-OpVt4(Unknown Source:0)
	at com.android.systemui.controls.controller.ControlsControllerImpl$loadForComponent$2$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

OS: Android 13 `OmniROM 13-202308121931-zenfone6-GAPPS`

**Comment by KieronQuinn** [comment]
I fucked up uploading the APK, download it again (same version) and it'll be fixed. It was missing this commit: https://github.com/KieronQuinn/ClassicPowerMenu/commit/2914e9736b9625faecec4fdcd098221cffb91bfb

(you were too quick, basically)
