### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by t0rzz** [KieronQuinn/ClassicPowerMenu#3]
Hi,
I have just installed the latest version of your app. After granting root permissions, the app force closes.
Any way to get the exact logs? Is there an automatic log reporting?

Thank you

**Comment by KieronQuinn** [comment]
There is no automatic  reporting, use something like https://f-droid.org/en/packages/taco.scoop/ to dump the logs please and upload them.

**Comment by t0rzz** [comment]
There you go:
`FATAL EXCEPTION: main
Process: com.kieronquinn.app.classicpowermenu, PID: 31570
java.lang.NullPointerException: isAccessibilityServiceEnabled$default must not be null
	at com.kieronquinn.app.classicpowermenu.utils.extensions.Extensions_AccessibilityServiceKt.isAccessibilityServiceEnabled$default(Extensions+AccessibilityService.kt:12)
	at com.kieronquinn.app.classicpowermenu.ui.screens.setup.rootcheck.SetupRootCheckViewModelImpl$showNext$1.invokeSuspend(SetupRootCheckViewModel.kt:50)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.kieronquinn.app.classicpowermenu.ui.screens.setup.rootcheck.SetupRootCheckViewModelImpl.showNext(SetupRootCheckViewModel.kt:49)
	at com.kieronquinn.app.classicpowermenu.ui.screens.setup.rootcheck.SetupRootCheckFragment.handleState(SetupRootCheckFragment.kt:38)
	at com.kieronquinn.app.classicpowermenu.ui.screens.setup.rootcheck.SetupRootCheckFragment.access$handleState(SetupRootCheckFragment.kt:12)
	at com.kieronquinn.app.classicpowermenu.ui.screens.setup.rootcheck.SetupRootCheckFragment$setupState$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:135)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:112)
	at androidx.lifecycle.DispatchQueue.access$enqueue(DispatchQueue.kt:31)
	at androidx.lifecycle.DispatchQueue$dispatchAndEnqueue$1$1.run(DispatchQueue.kt:100)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

Model S10+, latest firmware.

**Comment by t0rzz** [comment]
After reading the logs it was pretty straightforward that I had to enable your app in the accessibility settings. Although it didn't ask for it on first run. Now it's running fine, thank you.
