### ISSUE TITLE
Xposed module not working

### ISSUE THREAD

**Issue by telumletiferum** [KieronQuinn/ClassicPowerMenu#35]
I have tried enabling the Xposed module via Zygisk LSPosed on A11 and it doesn't seem to work. Only way I have gotten it to work is through Accessibility option.

**Comment by e0xify** [comment]
Same here. Doesnt popup anymore when xposed Module is enabled.

**Comment by C0unt-zero** [comment]
Device: Xiaomi Mi5
Android version: Android 11

Here is the log.
The error in the log does not seem to occur in 1.3.1, but now occurs in 1.4 (including 1.4.1).

[modules_2022-03-20T02_12_19.937.log](https://github.com/KieronQuinn/ClassicPowerMenu/files/8309765/modules_2022-03-20T02_12_19.937.log)

**Comment by KieronQuinn** [comment]
@telumletiferum @e0xify 

Please post your device info and send a log like C0unt-zero did. 

1.4.x merges a PR that adds MIUI 13 support, if you're all using MIUI it may explain it.

**Comment by e0xify** [comment]
![Uploading Screenshot_20220319-192743_Settings.jpg…]()

**Comment by telumletiferum** [comment]
I'm running Arrow OS on Mi 9 Lite. From what I've seen it doesn't produce any errors like it does for @C0unt-zero, but here are the logs anyway
[LSPosed_2022-03-19T20_50_54.517.zip](https://github.com/KieronQuinn/ClassicPowerMenu/files/8309898/LSPosed_2022-03-19T20_50_54.517.zip)

**Comment by e0xify** [comment]
![Uploading Screenshot_20220319-192743_Settings.jpg…]()

**Comment by e0xify** [comment]
.

**Comment by e0xify** [comment]
API Version
93

Injektionsschnittstelle
Zygisk

Framework Version
1.7.2 (6379)

Manager Version
1.7.2 (6379)

System Version
12 (API 31)

Gerät
Samsung SM-G988B 

System ABI
arm64-v8a

OneUI 4.0 Android 12

**Comment by KieronQuinn** [comment]
> API Version 93
> 
> Injektionsschnittstelle Zygisk
> 
> Framework Version 1.7.2 (6379)
> 
> Manager Version 1.7.2 (6379)
> 
> System Version 12 (API 31)
> 
> Gerät Samsung SM-G988B
> 
> System ABI arm64-v8a
> 
> OneUI 4.0 Android 12

OneUI is expected to not work, I don't support OEM skins unless support has been added by PR (like MIUI has)

**Comment by C0unt-zero** [comment]
Sorry, I will provide additional logs.
```
[ E/LSPosed-Bridge] java.lang.NoSuchFieldException: mDeviceProvisioned
	at java.lang.Class.getField(Class.java:1604)
	at com.kieronquinn.app.classicpowermenu.components.xposed.Xposed.hookAospSystemUI(Xposed.kt:93)
	at com.kieronquinn.app.classicpowermenu.components.xposed.Xposed.hookSystemUI(Xposed.kt:60)
	at com.kieronquinn.app.classicpowermenu.components.xposed.Xposed.handleLoadPackage(Xposed.kt:39)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:98)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:148)
	at org.lsposed.lspd.hooker.LoadedApkGetCLHooker.afterHookedMethod(LoadedApkGetCLHooker.java:90)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:455)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1214)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2655)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6602)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:442)
	at LSPHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7659)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
[LSPosed_2022-03-22T21_18_53.937.zip](https://github.com/KieronQuinn/ClassicPowerMenu/files/8324106/LSPosed_2022-03-22T21_18_53.937.zip)

**Comment by EugeneDP89** [comment]
Same happens to me on Pixel 4 Android 12, using Xposed module via Zygisk LSPosed.
[logcat.txt.zip](https://github.com/KieronQuinn/ClassicPowerMenu/files/8327214/logcat.txt.zip)

**Comment by hacker1024** [comment]
Fixed by changing the `getField` call to `getDeclaredField`.

Here's a debug-signed release build (rename to .apk): [app-release-aligned-debugSigned.zip](https://github.com/KieronQuinn/ClassicPowerMenu/files/8330183/app-release-aligned-debugSigned.zip)

**Comment by C0unt-zero** [comment]
I tried @hacker1024's build.

https://user-images.githubusercontent.com/82859690/159655144-6573b230-0fc0-457d-a520-b5c4a8a9ea1b.mp4

It works fine as in 1.3.x
No errors or crashes.

**Comment by telumletiferum** [comment]
@hacker1024's debug build works like a charm. Thank you kind sir!

**Comment by KieronQuinn** [comment]
I've put the fix into an official build (1.4.2). Thanks @hacker1024 for the fix!

**Comment by e0xify** [comment]
Guess there is no way to get it fixxed unless there is someone into doing in PR.

Anyway ill attach some logs. Just in case someone feels free to take a Look into it.

Guess the Samsung.kg.client is crashing (payment Services) and some Power.io issue with fatal exception

[LSPosed_2022-03-24T12_37_19.117.zip](https://github.com/KieronQuinn/ClassicPowerMenu/files/8341103/LSPosed_2022-03-24T12_37_19.117.zip)

**Comment by KieronQuinn** [comment]
> 

That's not related to this app. Support for OEM firmware **has** to be custom, logs aren't helpful here as they change too much.

**Comment by Manasx100** [comment]
Same issue MIUI 13
