### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by pbanj** [KieronQuinn/ClassicPowerMenu#4]
Not sure what caused it but scoop caught it. Only time it's crashed too. 

I'm using the lsposed mod and have it enabled in accessibility settings. 

`FATAL EXCEPTION: main
Process: com.kieronquinn.app.classicpowermenu, PID: 5967
java.lang.NullPointerException
	at com.kieronquinn.app.classicpowermenu.service.runner.CPMServiceRunner$bindService$1$1.invokeSuspend(CPMServiceRunner.kt:22)
	at com.kieronquinn.app.classicpowermenu.service.runner.CPMServiceRunner$bindService$1$1.invoke(Unknown Source:8)
	at com.kieronquinn.app.classicpowermenu.service.runner.CPMServiceRunner$bindService$1$1.invoke(Unknown Source:4)
	at com.kieronquinn.app.classicpowermenu.service.container.CPMServiceContainerImpl.runWithService(CPMServiceContainer.kt:37)
	at com.kieronquinn.app.classicpowermenu.service.container.CPMServiceContainerImpl$runWithService$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by KieronQuinn** [comment]
Fixed in 1.2
