### ISSUE TITLE
Error when tried to add controls

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/ClassicPowerMenu#75]
I am trying to add controls through the app but it is ultimately getting crashed and this is the error i am getting:

 java.lang.IllegalArgumentException:
com.kieronquinn.app.classicpowermenu: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
	at android.app.PendingIntent.getActivity(PendingIntent.java:470)
	at android.app.PendingIntent.getActivity(PendingIntent.java:434)
	at com.android.systemui.controls.controller.ControlsControllerImpl.createRemovedStatus(ControlsControllerImpl.kt:471)
	at com.android.systemui.controls.controller.ControlsControllerImpl.access$createRemovedStatus(ControlsControllerImpl.kt:54)
	at com.android.systemui.controls.controller.ControlsControllerImpl$loadForComponent$2.error$lambda-8(ControlsControllerImpl.kt:346)
	at com.android.systemui.controls.controller.ControlsControllerImpl$loadForComponent$2.$r8$lambda$YxWmGwmD8yhkmS3BiEzsgu6xpu8(Unknown Source:0)
	at com.android.systemui.controls.controller.ControlsControllerImpl$loadForComponent$2$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

Device - Realme 2 Pro

Android - v13

ROM - Arrow OS

Classic Power Menu version - v1.6

**Comment by DioVayne** [comment]
Same here on the Pixel 4a 5G on Android 13. Editing controls works, but adding controls crashes the app.

**Comment by DioVayne** [comment]
Same here. Is the developer still active or should we be looking for an alternative?

**Comment by rom4ster** [comment]
Same issue here

**Comment by rom4ster** [comment]
This issue comes up only in 1.7 the other builds are fine up to 1.62 which means it is likely a change related to the default assistant support

**Comment by KieronQuinn** [comment]
> This issue comes up only in 1.7 the other builds are fine up to 1.62 which means it is likely a change related to the default assistant support

Nothing to do with that. Most likely it's only impacting _you_ now, given others have reported it previous to that release.

**Comment by JLJTGR** [comment]
I'm pretty sure there are different issues here.  One above from the OP and one that is specific to 1.7.  Since you keep closing other similar issues, I guess I'll post here.

In 1.6.2 I can add Home tiles, in 1.7 I can only use tiles that were added by 1.6.2.  Clean installing 1.7 leaves me with zero tiles and attempting to add one crashes the app.  Eventually after a few crashes, Android disables the accessibility service and it won't open anymore.
[Log_2023-06-23_16-39-13.txt](https://github.com/KieronQuinn/ClassicPowerMenu/files/11852979/Log_2023-06-23_16-39-13.txt)
My logcat doesn't look like the OP.

Pixel 4 XL
Android `13`
Kernel `4.14.276-g6ef255005cea-ab9062920
#1 Wed Sep 14 08:05:09 UTC 2022`
Build `TP1A.221005.002.B2`

**Comment by rom4ster** [comment]
> 

This is the wrong issue for that most likely. 
Please see issue https://github.com/KieronQuinn/ClassicPowerMenu/issues/107

The fix is already accepted into the main branch but there is not a release. You can use the release I put there or you can compile the main branch and use that until the KieronQuinn makes a release.

**Comment by Jnss98b** [comment]
Just adding another anecdote that I have this exact problem too

_"In 1.6.2 I can add Home tiles, in 1.7 I can only use tiles that were added by 1.6.2. Clean installing 1.7 leaves me with zero tiles and attempting to add one crashes the app. Eventually after a few crashes, Android disables the accessibility service and it won't open anymore."_

**Comment by rom4ster** [comment]
> Just adding another anecdote that I have this exact problem too
> 
> _"In 1.6.2 I can add Home tiles, in 1.7 I can only use tiles that were added by 1.6.2. Clean installing 1.7 leaves me with zero tiles and attempting to add one crashes the app. Eventually after a few crashes, Android disables the accessibility service and it won't open anymore."_

Please look at issue 107 as I stated in my previous comment. That issue has a link that I created to a release that you can download or you can simply compile the app from the master branch and use that

**Comment by KieronQuinn** [comment]
Fixed in 1.7.1
